name: Build Fuzz

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: install deps
        run: go install github.com/dvyukov/go-fuzz/go-fuzz@latest && go install github.com/dvyukov/go-fuzz/go-fuzz-build@latest
      - name: build fuzz
        run: go-fuzz-build
        working-directory: fuzz
