name: Tests

on:
  pull_request:
  push:
    branches:
      - master
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goarch: ["arm64", "amd64"]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: install
        run: GOOS=linux GOARCH=${{ matrix.goarch }} go build

  tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        goarch: ["amd64"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: test & coverage report creation
        run: |
          GOARCH=${{ matrix.goarch }} go test -mod=readonly -timeout 8m -race -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
